POST http://localhost:8080/devices
Content-Type: application/json

{
    "name": "Z",
    "brand": "Moto",
    "state": "Active"
}

###

POST http://localhost:8080/devices
Content-Type: application/json

{
    "name": "Edge",
    "brand": "Moto",
    "state": "Active"
}

###

POST http://localhost:8080/devices
Content-Type: application/json

{
    "name": "galaxy s20",
    "brand": "Samsung",
    "state": "Active"
}

###

POST http://localhost:8080/devices
Content-Type: application/json

{
    "name": "galaxy s20",
    "brand": "Samsung",
    "state": "Disabled"
}

###

GET http://localhost:8080/devices/1

###

DELETE http://localhost:8080/devices/1

###

GET http://localhost:8080/devices/

###

GET http://localhost:8080/devices?brand=Samsung

###

GET http://localhost:8080/devices?brand=Moto

###

GET http://localhost:8080/devices?brand=Moto&name=Edge

###

GET http://localhost:8080/devices?brand=Moto&name=Edge&state=Active

###

GET http://localhost:8080/devices?state=Disabled