POST http://localhost:8080/devices
Content-Type: application/json

{
    "name": "Z",
    "brand": "Moto",
    "state": "available"
}

###

POST http://localhost:8080/devices
Content-Type: application/json

{
    "name": "Edge",
    "brand": "Moto",
    "state": "available"
}

###

POST http://localhost:8080/devices
Content-Type: application/json

{
    "name": "galaxy s20",
    "brand": "Samsung",
    "state": "active"
}

###

POST http://localhost:8080/devices
Content-Type: application/json

{
    "name": "galaxy s20",
    "brand": "Samsung",
    "state": "available"
}

###

PUT http://localhost:8080/devices/5
Content-Type: application/json

{
    "brand": "Samsung"
}

###

GET http://localhost:8080/devices/5

###

GET http://localhost:8080/devices/

###

GET http://localhost:8080/devices/5

###

DELETE http://localhost:8080/devices/1

###

GET http://localhost:8080/devices?brand=Samsung

###

GET http://localhost:8080/devices?brand=Moto

###

GET http://localhost:8080/devices?brand=Moto&name=Edge

###

GET http://localhost:8080/devices?brand=Moto&name=Edge&state=Active

###

GET http://localhost:8080/devices?state=Disabled